// app/appointments/verify/[intentId]/page.tsx
"use client";

import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { api, authHeader } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import Link from "next/link";

type ConfirmedAppt = {
  _id?: string;
  start?: string;
  end?: string;
  status?: string;
  mode?: string;
  therapist?: { name?: string } | string;
  patient?: { name?: string; patientId?: string } | string;
  createdAt?: string;
};

function fmt(dt: string) {
  return new Date(dt).toLocaleString(undefined, {
    weekday: "short", month: "short", day: "2-digit",
    hour: "2-digit", minute: "2-digit",
  });
}

function fmtTime(dt: string) {
  return new Date(dt).toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" });
}

function generateReceiptNo(id?: string, createdAt?: string): string {
  const base = createdAt ? new Date(createdAt) : new Date();
  const datePart = base.toISOString().slice(0, 10).replace(/-/g, "");
  const suffix = (id ?? "").slice(-5).toUpperCase() || Math.random().toString(36).slice(2, 7).toUpperCase();
  return `RCT-${datePart}-${suffix}`;
}

function ReceiptModal({ appt, email, fallbackId, onClose }: { appt: ConfirmedAppt; email: string; fallbackId?: string; onClose: () => void }) {
  const therapistName = typeof appt.therapist === "string" ? appt.therapist : appt.therapist?.name ?? "—";
  const patientObj = typeof appt.patient === "object" ? appt.patient : null;
  const patientName = patientObj?.name ?? (typeof appt.patient === "string" ? appt.patient : email);
  const ptNumber = patientObj?.patientId ?? null;
  const receiptNo = generateReceiptNo(appt._id ?? fallbackId, appt.createdAt);
  const printedOn = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "2-digit" });

  function saveReceipt() {
    const esc = (s: string) =>
      String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));

    const rows: Array<[string, string]> = [["Patient", patientName]];
    if (ptNumber) rows.push(["Patient ID", ptNumber]);
    if (therapistName !== "—") rows.push(["Therapist", therapistName]);
    if (appt.start) rows.push(["Date & Time", appt.end ? `${fmt(appt.start)} → ${fmtTime(appt.end)}` : fmt(appt.start)]);
    if (appt.mode) rows.push(["Mode", appt.mode === "online" ? "Online" : "In Person"]);
    rows.push(["Status", "Pending Confirmation"]);
    rows.push(["Saved on", printedOn]);

    const rowsHtml = rows
      .map(
        ([k, v]) =>
          `<tr><td style="color:#6b7280;padding:6px 0">${esc(k)}</td><td style="text-align:right;font-weight:500;color:#1f2937;padding:6px 0">${esc(v)}</td></tr>`
      )
      .join("");

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>TheraKonnect Receipt — ${esc(receiptNo)}</title>
<style>
  body { margin:0; background:#f3f4f6; font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif; padding:24px; }
  .card { max-width:380px; margin:0 auto; background:#fff; border-radius:16px; overflow:hidden; box-shadow:0 10px 30px rgba(0,0,0,0.08); }
  .head { background:linear-gradient(135deg,#3a5bef,#7c3aed); color:#fff; padding:20px 24px; }
  .head .brand { font-size:11px; letter-spacing:2px; text-transform:uppercase; opacity:0.8; }
  .head h2 { margin:4px 0 0; font-size:20px; }
  .head .num { margin-top:2px; font-size:11px; opacity:0.7; }
  table { width:100%; border-collapse:collapse; padding:0 24px; }
  .body { padding:16px 24px; font-size:14px; }
  .foot { background:#f9fafb; border-top:1px solid #f3f4f6; text-align:center; font-size:10px; color:#9ca3af; padding:12px 24px; }
  @media print { body { background:#fff; padding:0; } .card { box-shadow:none; } }
</style>
</head>
<body>
  <div class="card">
    <div class="head">
      <div class="brand">TheraKonnect</div>
      <h2>Appointment Receipt</h2>
      <div class="num">${esc(receiptNo)}</div>
    </div>
    <div class="body"><table>${rowsHtml}</table></div>
    <div class="foot">Generated by TheraKonnect · Keep this receipt for your records.</div>
  </div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `TheraKonnect-Receipt-${receiptNo}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <>
      <style>{`
        @media print {
          body > * { display: none !important; }
          #tk-receipt-overlay { display: flex !important; }
          #tk-receipt-overlay > div { box-shadow: none !important; }
          #tk-receipt-close-btn, #tk-receipt-print-btn-close { display: none !important; }
        }
      `}</style>
      <div
        id="tk-receipt-overlay"
        className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"
        onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
      >
        <div className="w-full max-w-sm rounded-2xl bg-white shadow-2xl">
          <div className="rounded-t-2xl bg-gradient-to-br from-[#3a5bef] to-[#7c3aed] px-6 py-5 text-white">
            <p className="text-xs font-semibold uppercase tracking-widest opacity-80">TheraKonnect</p>
            <h2 className="mt-1 text-xl font-bold">Appointment Receipt</h2>
            <p className="mt-0.5 text-xs opacity-70">{receiptNo}</p>
          </div>
          <div className="px-6 py-5 space-y-3 text-sm">
            <ReceiptRow label="Patient" value={patientName} />
            {ptNumber && <ReceiptRow label="Patient ID" value={ptNumber} />}
            {therapistName !== "—" && <ReceiptRow label="Therapist" value={therapistName} />}
            <div className="border-t border-dashed border-gray-200 pt-3 space-y-3">
              {appt.start && (
                <ReceiptRow
                  label="Date & Time"
                  value={appt.end ? `${fmt(appt.start)} → ${fmtTime(appt.end)}` : fmt(appt.start)}
                />
              )}
              {appt.mode && (
                <ReceiptRow label="Mode" value={appt.mode === "online" ? "Online" : "In Person"} />
              )}
              <ReceiptRow label="Status" value="Pending Confirmation" />
            </div>
            <div className="border-t border-dashed border-gray-200 pt-3">
              <ReceiptRow label="Printed on" value={printedOn} />
            </div>
          </div>
          <div className="rounded-b-2xl border-t border-gray-100 bg-gray-50 px-6 py-3 text-center text-[10px] text-gray-400">
            Generated by TheraKonnect · Keep this receipt for your records.
          </div>
          <div className="flex gap-2 px-6 py-4">
            <button
              onClick={saveReceipt}
              className="flex-1 rounded-xl bg-[#4b7eff] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#3a6bef] transition-colors"
            >
              💾 Save
            </button>
            <button
              id="tk-receipt-print-btn-close"
              onClick={onClose}
              className="flex-1 rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

function ReceiptRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4">
      <span className="text-gray-500 shrink-0">{label}</span>
      <span className="text-right font-medium text-gray-800">{value}</span>
    </div>
  );
}

export default function VerifyPage() {
  const router = useRouter();
  const { intentId } = useParams<{ intentId: string }>();
  const sp = useSearchParams();
  const email = sp.get("email") || "";
  const { token } = useAuth();

  const [code, setCode] = useState("");
  const [loading, setLoading] = useState(false);
  const [resending, setResending] = useState(false);
  const [err, setErr] = useState("");
  const [msg, setMsg] = useState("");
  const [confirmed, setConfirmed] = useState<ConfirmedAppt | null>(null);
  const [showReceipt, setShowReceipt] = useState(false);

  // Guard: if we somehow land here without an intentId or email, show a clear error
  const missingParams = !intentId || intentId === "undefined" || !email;

  async function onVerify() {
    setErr("");
    setMsg("");
    setLoading(true);
    try {
      // 1) Verify OTP for this intent
      await api("api/appointments/verify", {
        method: "POST",
        headers: {
          ...(token ? authHeader(token) : {}),
          "Content-Type": "application/json",
        } as HeadersInit,
        body: JSON.stringify({ intentId, email, code: code.trim() }),
      });

      // 2) Finalize booking
      const confirmRes = await api("api/appointments/confirm", {
        method: "POST",
        headers: {
          ...(token ? authHeader(token) : {}),
          "Content-Type": "application/json",
        } as HeadersInit,
        body: JSON.stringify({ intentId }),
      });

      // 3) Show confirmation screen with print receipt option
      const apptData: ConfirmedAppt = confirmRes?.appointment ?? confirmRes ?? {};
      setConfirmed(apptData);
    } catch (e: any) {
      setErr(e.message || "Verification failed. Please check your code and try again.");
    } finally {
      setLoading(false);
    }
  }

  async function onResend() {
    setErr("");
    setMsg("");
    setResending(true);
    try {
      await api("api/appointments/intent/resend", {
        method: "POST",
        headers: {
          ...(token ? authHeader(token) : {}),
          "Content-Type": "application/json",
        } as HeadersInit,
        body: JSON.stringify({ intentId, email }),
      });
      setMsg("A new code has been sent to " + email + ".");
      setCode("");
    } catch (e: any) {
      // Fallback: if the resend endpoint doesn't exist, guide the user
      setMsg("Please go back and restart the booking to get a new code.");
    } finally {
      setResending(false);
    }
  }

  if (missingParams) {
    return (
      <div className="min-h-[calc(100dvh-64px)] bg-gradient-to-br from-slate-50 via-blue-50/30 to-white flex items-center justify-center px-4 py-16">
        <div className="w-full max-w-md rounded-2xl border border-red-100 bg-white p-8 text-center shadow-md">
          <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-red-50">
            <svg className="h-7 w-7 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
            </svg>
          </div>
          <h1 className="text-lg font-semibold text-gray-900">Invalid verification link</h1>
          <p className="mt-2 text-sm text-gray-500">
            This link is missing required information. Please restart the booking process.
          </p>
          <Link
            href="/appointments/book"
            className="mt-5 inline-flex items-center rounded-xl bg-gradient-to-r from-[#4b7eff] to-[#6aa7ff] px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:brightness-105 transition-all"
          >
            Back to booking
          </Link>
        </div>
      </div>
    );
  }

  // ── Confirmation success screen ──
  if (confirmed) {
    return (
      <div className="min-h-[calc(100dvh-64px)] bg-gradient-to-br from-slate-50 via-blue-50/30 to-white flex items-center justify-center px-4 py-16">
        <div className="w-full max-w-md text-center">
          {/* Check icon */}
          <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-400/20 to-emerald-500/20 ring-1 ring-emerald-300/40">
            <svg className="h-8 w-8 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>

          <div className="rounded-2xl border border-gray-100 bg-white p-8 shadow-md">
            <h1 className="text-2xl font-semibold tracking-tight text-gray-900">Booking confirmed!</h1>
            <p className="mt-2 text-sm text-gray-500">
              Your appointment request has been submitted. You will receive a confirmation email once the therapist approves.
            </p>

            {/* Quick detail pills */}
            {confirmed.start && (
              <div className="mt-5 rounded-xl bg-gray-50 px-4 py-3 text-sm text-gray-700 text-left space-y-2">
                <div className="flex justify-between gap-2">
                  <span className="text-gray-400 text-xs">Date & Time</span>
                  <span className="font-medium text-xs text-right">
                    {fmt(confirmed.start)}{confirmed.end ? ` → ${fmtTime(confirmed.end)}` : ""}
                  </span>
                </div>
                {confirmed.mode && (
                  <div className="flex justify-between gap-2">
                    <span className="text-gray-400 text-xs">Mode</span>
                    <span className="font-medium text-xs">{confirmed.mode === "online" ? "Online" : "In Person"}</span>
                  </div>
                )}
                <div className="flex justify-between gap-2">
                  <span className="text-gray-400 text-xs">Status</span>
                  <span className="inline-flex items-center rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-medium text-amber-700 ring-1 ring-amber-200">
                    Pending confirmation
                  </span>
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="mt-6 flex flex-col gap-2">
              <button
                onClick={() => setShowReceipt(true)}
                className="w-full rounded-xl border-2 border-[#4b7eff]/30 bg-[#4b7eff]/5 px-4 py-2.5 text-sm font-semibold text-[#4b7eff] hover:bg-[#4b7eff]/10 transition-colors"
              >
                💾 Save Receipt
              </button>
              <Link
                href="/appointments/my"
                className="w-full rounded-xl bg-gradient-to-r from-[#4b7eff] to-[#6aa7ff] px-4 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:brightness-105 transition-all"
              >
                View My Appointments →
              </Link>
              <Link
                href="/appointments/book"
                className="text-xs text-gray-400 hover:text-gray-600 mt-1 transition-colors"
              >
                Book another appointment
              </Link>
            </div>
          </div>
        </div>

        {showReceipt && (
          <ReceiptModal
            appt={confirmed}
            email={email}
            fallbackId={intentId}
            onClose={() => setShowReceipt(false)}
          />
        )}
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100dvh-64px)] bg-gradient-to-br from-slate-50 via-blue-50/30 to-white flex items-center justify-center px-4 py-16">
      <div className="w-full max-w-md">
        {/* Icon */}
        <div className="mx-auto mb-6 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-[#4b7eff]/15 to-[#6aa7ff]/15 ring-1 ring-[#4b7eff]/20">
          <svg className="h-8 w-8 text-[#4b7eff]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.8}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
          </svg>
        </div>

        {/* Card */}
        <div className="rounded-2xl border border-gray-100 bg-white p-8 shadow-md">
          <div className="mb-6 text-center">
            <h1 className="text-2xl font-semibold tracking-tight text-gray-900">Verify your email</h1>
            <p className="mt-2 text-sm text-gray-600">
              We sent a 6-digit code to{" "}
              <span className="font-semibold text-gray-800">{email}</span>.
              Enter it below to confirm your appointment.
            </p>
          </div>

          {err && (
            <div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {err}
            </div>
          )}
          {msg && (
            <div className="mb-4 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">
              {msg}
            </div>
          )}

          <div className="space-y-5">
            <div>
              <label className="mb-1.5 block text-sm font-medium text-gray-700">
                Verification code
              </label>
              <input
                placeholder="1 2 3 4 5 6"
                value={code}
                onChange={(e) =>
                  setCode(e.target.value.replace(/\D/g, "").slice(0, 6))
                }
                maxLength={6}
                inputMode="numeric"
                autoComplete="one-time-code"
                className="w-full rounded-xl border border-gray-200 bg-white px-4 py-3 text-center text-2xl font-bold tracking-[0.4em] text-gray-900 shadow-sm transition-colors focus:outline-none focus:ring-2 focus:ring-[#4b7eff] focus:border-[#4b7eff]"
              />
              <p className="mt-1.5 text-center text-xs text-gray-400">
                {code.length}/6 digits entered
              </p>
            </div>

            <button
              onClick={onVerify}
              disabled={loading || code.length < 6}
              className="w-full rounded-xl py-2.5 text-sm font-semibold text-white bg-gradient-to-r from-[#4b7eff] to-[#6aa7ff] hover:brightness-105 active:brightness-95 shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#4b7eff] focus-visible:ring-offset-2 transition-all disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {loading ? (
                <span className="inline-flex items-center justify-center gap-2">
                  <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                  </svg>
                  Verifying…
                </span>
              ) : "Verify & Confirm Booking"}
            </button>

            <div className="flex items-center justify-center gap-4 text-sm">
              <button
                className="inline-flex items-center gap-1 text-gray-500 hover:text-[#4b7eff] hover:underline transition-colors disabled:opacity-50"
                onClick={onResend}
                disabled={resending}
              >
                {resending ? (
                  <>
                    <svg className="h-3 w-3 animate-spin" viewBox="0 0 24 24" fill="none">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
                    </svg>
                    Resending…
                  </>
                ) : "Resend code"}
              </button>
              <span className="text-gray-300">|</span>
              <Link href="/appointments/book" className="text-gray-500 hover:text-[#4b7eff] hover:underline transition-colors">
                Start over
              </Link>
            </div>
          </div>
        </div>

        <p className="mt-4 text-center text-xs text-gray-400">
          The code expires in 10 minutes. Check your spam folder if not received.
        </p>
      </div>
    </div>
  );
}
